name: Food App CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres_test
          POSTGRES_PASSWORD: postgres_test
          POSTGRES_DB: test
        ports:
          - 5433:5433

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.x
          
      - name: Install dependencies
        run: npm install

      - name: Setup Prisma
        run: npx prisma generate

      - name: Run Prisma Migrations
        env:
          DATABASE_URL: postgresql://postgres_test:postgres_test@postgres:5432/test
        run: npx prisma migrate deploy

      - name: Run tests
        run: npm test
