name: Food App CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: foodapp
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.x
          
      - name: Install dependencies
        run: npm install

      - name: Setup Prisma
        run: npx prisma generate

      - name: Apply Prisma Migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/foodapp
        run: npx prisma migrate deploy

      - name: Verify Tables
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/foodapp
        run: |
          sudo apt-get install postgresql-client
          PGPASSWORD=postgres psql -h localhost -U postgres -d foodapp -c '\dt'

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/foodapp
        run: npm test
