name: Food App CI

on:
  push:
    paths:
      - ./prisma/migrations/**
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASS }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.x
          
      - name: Install dependencies
        run: npm install

      - name: Setup Prisma
        run: npx prisma generate

      - name: Run Prisma Migrations
        env:
          DATABASE_URL: ${{ secrets.PRISMA_DATABASE_URL }}
        run: npx prisma migrate dev && npx prisma migrate deploy

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.PRISMA_DATABASE_URL }}
        run: npm test
